/* Fixed, uniformly volume-charged spheres, without polarization. SI units.
 * See docs/charged-spheres-model.md for derivation and numerical validation.
 */
(function (root, factory) {
  'use strict';
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  if (root) root.ChargedSpheresPhysics = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';

  const K = 8.9875517923e9;
  const EPSILON_0 = 1 / (4 * Math.PI * K);
  const quadratureCache = new Map();

  function finite(value, name) {
    if (!Number.isFinite(value)) throw new TypeError(name + ' must be finite');
    return value;
  }

  function accumulator() { return { value: 0, correction: 0 }; }
  function add(sum, value) {
    const adjusted = value - sum.correction;
    const next = sum.value + adjusted;
    sum.correction = (next - sum.value) - adjusted;
    sum.value = next;
  }

  function solve(options) {
    if (!options || typeof options !== 'object') throw new TypeError('solve requires an options object');
    const radiusA = finite(options.radiusA === undefined ? options.radius : options.radiusA, 'radiusA');
    const radiusB = finite(options.radiusB === undefined ? options.radius : options.radiusB, 'radiusB');
    const separation = finite(options.separation, 'separation');
    const q1 = finite(options.q1, 'q1');
    const q2 = finite(options.q2, 'q2');
    if (!(radiusA > 0 && radiusB > 0)) throw new RangeError('radii must be positive');
    if (!(separation > radiusA + radiusB)) throw new RangeError('spheres must not touch or overlap: separation > radiusA + radiusB');
    if (options.model !== undefined && options.model !== 'uniform') throw new RangeError('model must be uniform');
    const centers = [-separation / 2, separation / 2];
    const force = K * q1 * q2 / (separation * separation) || 0;
    const interactionEnergy = K * q1 * q2 / separation;
    return {
      model: 'uniform', radius: radiusA, radiusA, radiusB, radii: [radiusA, radiusB],
      separation, gap: separation - radiusA - radiusB, q1, q2, centers,
      volumeDensities: [3 * q1 / (4 * Math.PI * radiusA ** 3), 3 * q2 / (4 * Math.PI * radiusB ** 3)],
      force, coulombForce: force, ratio: force === 0 ? null : 1,
      interactionEnergy,
      // Total electrostatic energy includes the fixed self-energies of the balls.
      energy: interactionEnergy + 3 * K / 5 * (q1 * q1 / radiusA + q2 * q2 / radiusB),
      centerPotentials: [K * (3 * q1 / (2 * radiusA) + q2 / separation), K * (3 * q2 / (2 * radiusB) + q1 / separation)],
      converged: true, errorEstimate: 0,
      forceConvention: 'force on sphere B (right): positive repulsion, negative attraction'
    };
  }

  function fieldFromSphere(solution, sphere, x, y) {
    const radius = solution.radii[sphere];
    const q = sphere === 0 ? solution.q1 : solution.q2;
    const dx = x - solution.centers[sphere];
    const r = Math.hypot(dx, y);
    // The solid sphere's interior field is linear in the center displacement.
    const factor = K * q / (r < radius ? radius ** 3 : r ** 3);
    return {
      ex: factor * dx, ey: factor * y,
      potential: r < radius ? K * q * (3 * radius ** 2 - r ** 2) / (2 * radius ** 3) : K * q / r,
      inside: r < radius
    };
  }

  function fieldAt(solution, x, y) {
    finite(x, 'x'); finite(y, 'y');
    const a = fieldFromSphere(solution, 0, x, y);
    const b = fieldFromSphere(solution, 1, x, y);
    const ex = a.ex + b.ex;
    const ey = a.ey + b.ey;
    return { ex, ey, x: ex, y: ey, potential: a.potential + b.potential, inside: a.inside || b.inside, sphere: a.inside ? 0 : b.inside ? 1 : -1 };
  }

  // Local force per unit volume on sphere B. Only A's electric field acts in
  // this interaction; B's self-field is excluded. The charge density is fixed.
  function sampleForce(solution, x, y) {
    finite(x, 'x'); finite(y, 'y');
    const a = fieldFromSphere(solution, 0, x, y);
    const insideB = Math.hypot(x - solution.centers[1], y) <= solution.radiusB * (1 + 1e-12);
    const rho = insideB ? solution.volumeDensities[1] : 0;
    return { ex: a.ex, ey: a.ey, rho, insideB, forceDensityX: rho * a.ex, forceDensityY: rho * a.ey };
  }

  // Gauss-Legendre nodes and weights on [-1, 1], generated by Newton iteration.
  function gaussLegendre(order) {
    if (!(Number.isInteger(order) && order >= 2 && order <= 96)) throw new RangeError('order must be an integer from 2 to 96');
    if (quadratureCache.has(order)) return quadratureCache.get(order);
    const nodes = new Array(order);
    const weights = new Array(order);
    for (let i = 0; i < Math.ceil(order / 2); i += 1) {
      let z = Math.cos(Math.PI * (i + 0.75) / (order + 0.5));
      let derivative = 0;
      for (let iteration = 0; iteration < 50; iteration += 1) {
        let previous = 1;
        let current = z;
        for (let n = 2; n <= order; n += 1) {
          const next = ((2 * n - 1) * z * current - (n - 1) * previous) / n;
          previous = current;
          current = next;
        }
        derivative = order * (z * current - previous) / (z * z - 1);
        const change = current / derivative;
        z -= change;
        if (Math.abs(change) < 2e-15) break;
      }
      // Recompute the derivative at the final root for consistent weights.
      let previous = 1;
      let current = z;
      for (let n = 2; n <= order; n += 1) {
        const next = ((2 * n - 1) * z * current - (n - 1) * previous) / n;
        previous = current;
        current = next;
      }
      derivative = order * (z * current - previous) / (z * z - 1);
      const weight = 2 / ((1 - z * z) * derivative * derivative);
      nodes[i] = -z;
      nodes[order - 1 - i] = z;
      weights[i] = weight;
      weights[order - 1 - i] = weight;
    }
    const result = { nodes, weights };
    quadratureCache.set(order, result);
    return result;
  }

  // A circular slice at u = (x - x_B)/R_B. Returned charge and force are
  // per unit u; multiply by du (or a quadrature weight) for a contribution.
  function sliceAt(solution, u, order = 12) {
    finite(u, 'u');
    if (u < -1 || u > 1) throw new RangeError('slice u must be between -1 and 1');
    const rule = gaussLegendre(order);
    const areaFactor = Math.max(0, 1 - u * u);
    const x = solution.centers[1] + solution.radiusB * u;
    const discRadius = solution.radiusB * Math.sqrt(areaFactor);
    const meanField = accumulator();
    for (let i = 0; i < order; i += 1) {
      const t = (rule.nodes[i] + 1) / 2;
      const weight = rule.weights[i] / 2;
      const field = fieldFromSphere(solution, 0, x, discRadius * t);
      add(meanField, 2 * t * weight * field.ex);
    }
    const chargePerU = 3 * solution.q2 / 4 * areaFactor;
    return { u, x, discRadius, chargePerU, forcePerU: chargePerU * meanField.value, fieldX: meanField.value };
  }

  function integrateForce(params, order = 12) {
    const solution = params && params.radii && params.centers ? params : solve(params);
    const rule = gaussLegendre(order);
    const force = accumulator();
    const charge = accumulator();
    const slices = [];
    let nearForce = 0;
    let farForce = 0;
    // Integrate each hemisphere separately, so their contributions have the
    // same smooth quadrature accuracy as the total (no step-function mask).
    for (let half = 0; half < 2; half += 1) {
      for (let i = 0; i < order; i += 1) {
        const u = (rule.nodes[i] + (half === 0 ? -1 : 1)) / 2;
        const weight = rule.weights[i] / 2;
        const slice = sliceAt(solution, u, order);
        const weightedCharge = slice.chargePerU * weight;
        const weightedForce = slice.forcePerU * weight;
        slices.push({ u: slice.u, x: slice.x, charge: weightedCharge, force: weightedForce, fieldX: slice.fieldX, weight });
        add(force, weightedForce);
        add(charge, weightedCharge);
        if (half === 0) nearForce += weightedForce;
        else farForce += weightedForce;
      }
    }
    const relativeError = solution.force === 0 ? null : Math.abs((force.value - solution.force) / solution.force);
    return {
      force: force.value, numericalForce: force.value, exactForce: solution.force,
      relativeError, absoluteError: Math.abs(force.value - solution.force),
      samples: 2 * order * order, order, slices, integratedCharge: charge.value,
      nearForce, farForce
    };
  }

  function volumePoints(solution, sphere, gridSize) {
    const radius = solution.radii[sphere];
    const points = [];
    const spacing = 2 / gridSize;
    for (let i = 0; i < gridSize; i += 1) {
      const u = -1 + (i + 0.5) * spacing;
      for (let j = 0; j < gridSize; j += 1) {
        const v = -1 + (j + 0.5) * spacing;
        for (let k = 0; k < gridSize; k += 1) {
          const w = -1 + (k + 0.5) * spacing;
          if (u * u + v * v + w * w <= 1 + 1e-12) {
            points.push({ x: solution.centers[sphere] + radius * u, y: radius * v, z: radius * w, q: 0 });
          }
        }
      }
    }
    const pointCharge = (sphere === 0 ? solution.q1 : solution.q2) / points.length;
    for (const point of points) point.q = pointCharge;
    return points;
  }

  function validateGridSize(gridSize) {
    if (!(Number.isInteger(gridSize) && gridSize >= 3 && gridSize <= 15 && gridSize % 2 === 1)) {
      throw new RangeError('gridSize must be an odd integer from 3 to 15');
    }
  }

  // Compare the nearest and farthest actual voxel centers ON the horizontal
  // sphere-center line. Their y and z coordinates are zero on an odd grid.
  // This gives a simple axial comparison, rather than a 3D farthest-pair search.
  function axisPairs(params, gridSize = 7) {
    const solution = params && params.radii && params.centers ? params : solve(params);
    validateGridSize(gridSize);
    const pointsA = volumePoints(solution, 0, gridSize);
    const pointsB = volumePoints(solution, 1, gridSize);
    const axisA = pointsA.filter(point => point.y === 0 && point.z === 0);
    const axisB = pointsB.filter(point => point.y === 0 && point.z === 0);
    // volumePoints lists each axis's x coordinates from left to right.
    const nearPoints = [axisA[axisA.length - 1], axisB[0]];
    const farPoints = [axisA[0], axisB[axisB.length - 1]];
    function describe(points) {
      const distance = points[1].x - points[0].x;
      const squared = distance * distance;
      const signedForce = K * points[0].q * points[1].q / squared || 0;
      return {
        distance, force: Math.abs(signedForce), signedForce,
        forceVector: { x: signedForce, y: 0, z: 0 },
        points
      };
    }
    const near = describe(nearPoints);
    const far = describe(farPoints);
    return {
      near, far,
      forceRatio: solution.q1 === 0 || solution.q2 === 0 ? null : (far.distance / near.distance) ** 2,
      gridSize, pairs: pointsA.length * pointsB.length,
      pointsPerSphere: pointsA.length, pointCounts: [pointsA.length, pointsB.length],
      comparisonAxis: 'x', axisPointCounts: [axisA.length, axisB.length],
      selection: 'voxel centers on the sphere-center line (y = z = 0)',
      forceConvention: 'force is the nonnegative pair-force magnitude; signedForce is positive for repulsion; forceVector acts on B'
    };
  }

  // Deliberately independent of sphere-field formulas: approximate BOTH balls
  // by equal-volume voxel-center charges and apply Coulomb to every A-B pair.
  // The selected boundary voxels approximate a curved ball; finite grids are
  // not exactly rotationally symmetric and their force can differ from Fc.
  function directSumForce(params, gridSize = 7) {
    const solution = params && params.radii && params.centers ? params : solve(params);
    validateGridSize(gridSize);
    const pointsA = volumePoints(solution, 0, gridSize);
    const pointsB = volumePoints(solution, 1, gridSize);
    const fx = accumulator();
    const fy = accumulator();
    const fz = accumulator();
    const near = accumulator();
    const far = accumulator();
    const layers = new Map();
    for (const point of pointsB) {
      if (!layers.has(point.x)) layers.set(point.x, { x: point.x, u: (point.x - solution.centers[1]) / solution.radiusB, sum: accumulator(), pointCount: 0 });
      layers.get(point.x).pointCount += 1;
    }
    const pairFactor = K * pointsA[0].q * pointsB[0].q;
    if (pairFactor !== 0) {
      for (const b of pointsB) {
        const pointX = accumulator();
        const pointY = accumulator();
        const pointZ = accumulator();
        for (const a of pointsA) {
          const dx = b.x - a.x;
          const dy = b.y - a.y;
          const dz = b.z - a.z;
          const rSquared = dx * dx + dy * dy + dz * dz;
          const factor = pairFactor / (rSquared * Math.sqrt(rSquared));
          add(pointX, factor * dx);
          add(pointY, factor * dy);
          add(pointZ, factor * dz);
        }
        add(fx, pointX.value);
        add(fy, pointY.value);
        add(fz, pointZ.value);
        add(layers.get(b.x).sum, pointX.value);
        const localX = b.x - solution.centers[1];
        if (localX < -solution.radiusB * 1e-12) add(near, pointX.value);
        else if (localX > solution.radiusB * 1e-12) add(far, pointX.value);
        else { add(near, pointX.value / 2); add(far, pointX.value / 2); }
      }
    }
    const baseline = Math.abs(solution.force);
    const signedRelativeError = baseline === 0 ? null : (fx.value - solution.force) / baseline;
    const magnitudeRelativeError = baseline === 0 ? null : (Math.abs(fx.value) - baseline) / baseline;
    const slices = Array.from(layers.values(), function (layer) {
      return { u: layer.u, x: layer.x, force: layer.sum.value, charge: layer.pointCount * pointsB[0].q, pointCount: layer.pointCount };
    });
    return {
      force: fx.value, numericalForce: fx.value, forceY: fy.value, forceZ: fz.value,
      exactForce: solution.force, gridSize,
      relativeError: baseline === 0 ? null : Math.abs(signedRelativeError),
      signedRelativeError, magnitudeRelativeError,
      absoluteError: Math.abs(fx.value - solution.force),
      pairs: pointsA.length * pointsB.length,
      pointCount: pointsA.length + pointsB.length,
      pointsPerSphere: pointsA.length, pointCounts: [pointsA.length, pointsB.length],
      pointsA, pointsB, slices, nearForce: near.value, farForce: far.value
    };
  }

  return { K, EPSILON_0, solve, fieldAt, sampleForce, sliceAt, integrateForce, directSumForce, axisPairs };
});
